### PR TITLE
Remove Taas service feature

### PR DESCRIPTION
**Pull request by miurahr**
Signed-off-by: Hiroshi Miura <miurahr@linux.com>

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Build and release changes
- [x] Other (describe below)

## Which ticket is resolved?

- Link: 
- Title: 

## What does this PR change?

-
-
-

### CODE REVIEW

**Comment by miurahr** [comment]
Need to remove `TAAS_*` keys from `Bundle_*.properties`

**Comment by miurahr** [comment]
> Need to remove `TAAS_*` keys from `Bundle_*.properties`

done

**Comment by brandelune** [comment]
Screen Shot 2022-10-02 at 21 08 37

Otherwise, it looks good.

**Comment by miurahr** [comment]
> Otherwise, it looks good.

TODO:
- remove Empty UI menu.

**Comment by miurahr** [comment]
> > Otherwise, it looks good.
> 
> TODO:
> 
> * remove Empty UI menu.

This should not remove because 3rd party plugin may use it. It is in `IMainMenu` interface class that is a promise to plugins.

**Comment by brandelune** [comment]
Do we have a mechanism to not display it when it is empty ?

**Comment by miurahr** [comment]
> Do we have a mechanism to not display it when it is empty ?

Good idea!

**Comment by miurahr** [comment]
Make Preference->Glossary  menu has item fuzzy match

**Comment by brandelune** [comment]
Nice addition. It builds and runs fine.

**Comment by miurahr** [comment]
merged to master.

**Pull request merged**
