### PR TITLE
Fix NullPointerException in filters dialog

### PR DESCRIPTION
**Pull request by chelobaka**
I'm not sure if this bug is specific to my setup but I noticed it some time ago. NPE happens when I open filters dialog and click on one of the filters.

### CODE REVIEW

**Comment by amake** [comment]
We can add this null check, but I'd like to know why the value is null. Do you have any custom filters or plugins?

**Comment by chelobaka** [comment]
No custom filters or plugins, latest master. Probably Linux specific.

Error stack trace:

31709: Ошибка: Uncatched exception in thread [AWT-EventQueue-1] 
31709: Ошибка: java.lang.NullPointerException 
31709: Ошибка: 	at org.omegat.gui.filters2.FiltersCustomizer$FilterFormatCellRenderer.getTableCellRendererComponent(FiltersCustomizer.java:482) 
31709: Ошибка: 	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7031) 
31709: Ошибка: 	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7418) 
31709: Ошибка: 	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6933) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415) 
31709: Ошибка: 	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459) 
31709: Ошибка: 	at javax.swing.JTable.changeSelectionModel(JTable.java:2389) 
31709: Ошибка: 	at javax.swing.JTable.changeSelection(JTable.java:2458) 
31709: Ошибка: 	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1115) 
31709: Ошибка: 	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038) 
31709: Ошибка: 	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) 
31709: Ошибка: 	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) 
31709: Ошибка: 	at java.awt.Component.processMouseEvent(Component.java:6530) 
31709: Ошибка: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) 
31709: Ошибка: 	at java.awt.Component.processEvent(Component.java:6298) 
31709: Ошибка: 	at java.awt.Container.processEvent(Container.java:2236) 
31709: Ошибка: 	at java.awt.Component.dispatchEventImpl(Component.java:4889) 
31709: Ошибка: 	at java.awt.Container.dispatchEventImpl(Container.java:2294) 
31709: Ошибка: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) 
31709: Ошибка: 	at java.awt.Container.dispatchEventImpl(Container.java:2280) 
31709: Ошибка: 	at java.awt.Window.dispatchEventImpl(Window.java:2746) 
31709: Ошибка: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
31709: Ошибка: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) 
31709: Ошибка: 	at java.awt.EventQueue.access$500(EventQueue.java:97) 
31709: Ошибка: 	at java.awt.EventQueue$3.run(EventQueue.java:709) 
31709: Ошибка: 	at java.awt.EventQueue$3.run(EventQueue.java:703) 
31709: Ошибка: 	at java.security.AccessController.doPrivileged(Native Method) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) 
31709: Ошибка: 	at java.awt.EventQueue$4.run(EventQueue.java:731) 
31709: Ошибка: 	at java.awt.EventQueue$4.run(EventQueue.java:729) 
31709: Ошибка: 	at java.security.AccessController.doPrivileged(Native Method) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) 
31709: Ошибка: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) 
31709: Ошибка: 	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) 
31709: Ошибка: 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) 
31709: Ошибка: 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) 
31709: Ошибка: 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) 
31709: Ошибка: 	at java.security.AccessController.doPrivileged(Native Method) 
31709: Ошибка: 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) 
31709: Ошибка: 	at java.awt.Dialog.show(Dialog.java:1084) 
31709: Ошибка: 	at java.awt.Component.show(Component.java:1671) 
31709: Ошибка: 	at java.awt.Component.setVisible(Component.java:1623) 
31709: Ошибка: 	at java.awt.Window.setVisible(Window.java:1014) 
31709: Ошибка: 	at java.awt.Dialog.setVisible(Dialog.java:1005) 
31709: Ошибка: 	at org.omegat.gui.main.MainWindowMenuHandler.optionsSetupFileFiltersMenuItemActionPerformed(MainWindowMenuHandler.java:976) 
31709: Ошибка: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
31709: Ошибка: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
31709: Ошибка: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
31709: Ошибка: 	at java.lang.reflect.Method.invoke(Method.java:498) 
31709: Ошибка: 	at org.omegat.gui.main.MainWindowMenu.invokeAction(MainWindowMenu.java:152) 
31709: Ошибка: 	at org.omegat.gui.main.MainWindowMenu.actionPerformed(MainWindowMenu.java:124) 
31709: Ошибка: 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) 
31709: Ошибка: 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) 
31709: Ошибка: 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) 
31709: Ошибка: 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) 
31709: Ошибка: 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) 
31709: Ошибка: 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833) 
31709: Ошибка: 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877) 
31709: Ошибка: 	at java.awt.Component.processMouseEvent(Component.java:6533) 
31709: Ошибка: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) 
31709: Ошибка: 	at java.awt.Component.processEvent(Component.java:6298) 
31709: Ошибка: 	at java.awt.Container.processEvent(Container.java:2236) 
31709: Ошибка: 	at java.awt.Component.dispatchEventImpl(Component.java:4889) 
31709: Ошибка: 	at java.awt.Container.dispatchEventImpl(Container.java:2294) 
31709: Ошибка: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) 
31709: Ошибка: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) 
31709: Ошибка: 	at java.awt.Container.dispatchEventImpl(Container.java:2280) 
31709: Ошибка: 	at java.awt.Window.dispatchEventImpl(Window.java:2746) 
31709: Ошибка: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
31709: Ошибка: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) 
31709: Ошибка: 	at java.awt.EventQueue.access$500(EventQueue.java:97) 
31709: Ошибка: 	at java.awt.EventQueue$3.run(EventQueue.java:709) 
31709: Ошибка: 	at java.awt.EventQueue$3.run(EventQueue.java:703) 
31709: Ошибка: 	at java.security.AccessController.doPrivileged(Native Method) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) 
31709: Ошибка: 	at java.awt.EventQueue$4.run(EventQueue.java:731) 
31709: Ошибка: 	at java.awt.EventQueue$4.run(EventQueue.java:729) 
31709: Ошибка: 	at java.security.AccessController.doPrivileged(Native Method) 
31709: Ошибка: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) 
31709: Ошибка: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) 
31709: Ошибка: 	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
31709: Ошибка: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
31709: Ошибка: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by amake** [comment]
I can't reproduce in my Ubuntu 16.04 VM. What distro are you using?

**Comment by chelobaka** [comment]
It's Debian Testing with Cinnamon Desktop 3.0.7 and Mate Desktop 1.16: it happens in both. Java is OpenJDK 1.8.0_102 (64-bit).

**Comment by amake** [comment]
I was able to reproduce in a Debian VM. I guess it's just an artifact of the default LAF in that environment.

I applied your patch to trunk.

**Comment by chelobaka** [comment]
Thank you!

**Pull request closed without merging**
