### PR TITLE
Improve reuse of a backup project files

### PR DESCRIPTION
**Pull request by miurahr**
This change intend to improve an error handler and retry backup file when loading `omegat.project`

A root cause of the problem is a change #280 and #255 is not well integrated.

## Pull request type

Please mark github LABEL of the type of change your PR introduces:

- Bug fix -> [bug]

## Which ticket is resolved?

- Error displayed when opening a project on Windows 10
  * https://sourceforge.net/p/omegat/bugs/1136/

## What does this PR change?

- Reuse backup files.
- Pick a latest backup file
- When project file are broken, reuse backup file
- Don't copy backup file to project file
- Don't produce `omegat.project.bak` file.

### CODE REVIEW

**Review by briacp — COMMENTED** [review]
Thanks for the fix, this looks good.

**Comment by miurahr** [comment]
Thanks @briacp for review. merged into master now.

**Comment by miurahr** [comment]
Original issuer also confirmed the fix.

**Comment by miurahr** [comment]
The issue was enrolled after v5.7.1, so we don't need to add it to changelog

**Comment by miurahr** [comment]
#280 make backup file every time when successfully loading project file, but #255 make it when project file is changed.
If user just generated a project and doesn't change it, or just downloading team project, there is not a backup file.

**Pull request closed without merging**
