### PR TITLE
Project>Reload  load remote project configuration when team project

### PR DESCRIPTION
**Pull request by miurahr**
## Pull request type

- New feature [enhancement]

## Which ticket is resolved?

- Local project does not update after remote masking some files
   https://sourceforge.net/p/omegat/bugs/1124/

## What does this PR change?

- Load remote omegat.project when project is on team
- Refactoring `ProjectUICommands` class
-

### CODE REVIEW

**Comment by brandelune** [comment]
Do we need a "Reload _team_ project" menu item ? Can't it be the same "Reload project" item that calls 2 different functions depending on the status of the project ?

**Comment by miurahr** [comment]
see. https://sourceforge.net/p/omegat/bugs/1124/

**Comment by brandelune** [comment]
Your code logic detects that a project is a team project and acts on that.

Are you suggesting that we give 2 possibilities to team members: reload the _local_ info only and also reload the _remote_ info?

**Comment by miurahr** [comment]
> Your code logic detects that a project is a team project and acts on that.
> 
> Are you suggesting that we give 2 possibilities to team members: reload the _local_ info only and also reload the _remote_ info?

So we need to two menu item  reload local and reload remote

**Comment by brandelune** [comment]
What about

`Reload Project`

and

`Update Remote Project Information`

?

**Comment by msoutopico** [comment]
Thanks for your work, Hiroshi.

I haven't understood why the `Reload project` option cannot be used to update remote files, as JC suggests. Is it because it may be very slow? 

In fact, I wasn't aware that one could reload the project and update local files but not remote files... I had always assumed that `Reload project` (F5) (or when I use the `LOAD eventType` in a groovy script) is equivalent to closing and re-opening the project, but it seems that I got that wrong. 

Would `Reload project` be enough to fetch new or updated files from mapped repositories or would users need to run the new `Reload team project` for that?

**Comment by miurahr** [comment]
> I haven't understood why the `Reload project` option cannot be used to update remote files, as JC suggests. Is it because it may be very slow?

Yes super slow. Is is really acceptable? Really no need local reload even on team project?

**Comment by miurahr** [comment]
@brandelune now  Project > reload  is going to  download remote configuration.

**Comment by miurahr** [comment]
merged into `master`

**Comment by brandelune** [comment]
Can you check that a normal reload on a non-team project works on your side ? It looks locked on my side, but works for team-projects...

**Comment by miurahr** [comment]
Thanks for the check.
`GitRemoteRepository2IT#isTeamProject` raises a null pointer exception.

**Comment by miurahr** [comment]
A fix 0c8e173e is pushed to `master` on the sourceforge git repository.

**Pull request closed without merging**
