### PR TITLE
Double-check the clarified links in the How To chapter

### PR DESCRIPTION
**Pull request by Kazephil**
[documentation]

Only the Introduction was finished when #371 was merged.

This PR contains corrections to the How To chapter.

### CODE REVIEW

**Comment by Kazephil** [comment]
@brandelune
Please take a look at these changes.

**Comment by brandelune** [comment]
@Kazephil 
https://github.com/omegat-org/omegat/pull/350#issuecomment-1356239163

**Comment by brandelune** [comment]
Thank you ! Now, do a `git rebase -i` and force push as explained above!

**Comment by Kazephil** [comment]
> Thank you ! Now, do a `git rebase -i` and force push as explained above!

Doesn't work.

Running `git rebase -i` doesn't start an interactive editor to let me pick one commit and squash the others. I just get a "Successfully rebased and updated refs/heads/manual/checkClarifiedLinks." message, and nothing changes.

(I tried from the terminal and GUI tool, and directly from the command line outside my editor. Same result every time.)

**Comment by brandelune** [comment]
> > Thank you ! Now, do a `git rebase -i` and force push as explained above!

https://github.com/omegat-org/omegat/pull/350#issuecomment-1356239163

**Comment by Kazephil** [comment]
Sorry, I wasn't specific enough.

I had already tried with `git rebase -i HEAD~8` (and just tried again, to make sure), but I never get the interactive editor, only the "Sucessfully rebased and updated..." message.

It's a complete mystery.

**Comment by brandelune** [comment]
@miurahr We are a bit stuck here. Could you tell us what needs to be done to fix this commit?

**Comment by miurahr** [comment]
There is no problem. I've merged into `master`.

**Pull request closed without merging**
