### PR TITLE
Clarify link targets and add various missing parts

### PR DESCRIPTION
**Pull request by brandelune**
The localization process identified issues with the way the manual was written.

There are *very* few  additions in terms of information.
Most of the modifications are regarding links to other parts of the manual.

→ I've tried to systematically include the target type into the sentence.

`See <l1/> for details.`
is now:
`See the <l1/> chapter for details.`

etc.

I've also tried to homogenize wordings. For ex.

`To achieve this and that, you can use <m1/> in the <m2/> menu.`

is now:

`Use <m2/><m1/> to achieve this.`

where menu items are systematically in pairs with <root menu name><menu item name> and in 95% of the case they are prefixed with the verb "use".

Buttons are "click on ..."

Preferences are either "enable" or "see".

Etc.

### CODE REVIEW

**Review by kosivantsov — COMMENTED** [review]
Looks fine to me.

**Comment by Kazephil** [comment]
I just cloned this and built the documentation.

Give me a day or two to read through it and make sure the new homogenized wording hasn't accidentally created awkward phrasing when the links are expanded in the full text.

**Comment by brandelune** [comment]
What I did was:
- fix the indentation
- build the thing
- check the HTML for the wording around the links
- modify the wording
- build the thing
- check again, etc.

Basically, everything was validated as XML during the build process and as "English" in the HTML output.

**Comment by miurahr** [comment]
I'll wait @Kazephil to review it before merging.

**Comment by brandelune** [comment]
> Whenever I validate my own "English" in the HTML output, I miss something that gets pointed out by someone else... 😀 I'll try to get through the changes by tomorrow night.

In all honesty, I did not take the time to make grammar/spell checks.

**Comment by miurahr** [comment]
Rebase, squashed and merged into `master`

**Pull request closed without merging**
