### PR TITLE
Gradle: add jacoco verification rules

### PR DESCRIPTION
**Pull request by miurahr**
## Pull request type

- Build and release changes -> [build/release]

## Which ticket is resolved?

N.A.

## What does this PR change?

- Add Jacoco configurations to detect  packages/classes without unit test
  - Set minimum coverage to 20%
  - Exclude generated code, data class, gui classes
- It is not mandatory; comment out check dependency

## Other information

[What is a reasonable code coverage?](https://stackoverflow.com/a/90021/4467057)

### CODE REVIEW

**Comment by miurahr** [comment]
When running `./gradlew jacocoTestCoverageVerification` with the change, we can find classes/packages that don't have unit test as follows.

```
Execution failed for task ':jacocoTestCoverageVerification'.
> Rule violated for package org.omegat.core.spellchecker: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for package org.omegat.core.search: instructions covered ratio is 0.04, but expected minimum is 0.20
  Rule violated for package org.omegat.core.segmentation.datamodels: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.Google2Translate: instructions covered ratio is 0.12, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MicrosoftTranslatorAzure.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.DeepLTranslate: instructions covered ratio is 0.14, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.Google2Translate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MyMemoryMachineTranslate: instructions covered ratio is 0.05, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.ApertiumTranslate.2: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.ApertiumTranslate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.ApertiumTranslate.3: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MachineTranslators: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.YandexCloudTranslate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.ApertiumTranslate: instructions covered ratio is 0.10, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.DeepLTranslate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.IBMWatsonTranslate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MyMemoryHumanTranslate: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.IBMWatsonTranslate: instructions covered ratio is 0.15, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MicrosoftTranslatorAzure: instructions covered ratio is 0.02, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.BaseTranslate: instructions covered ratio is 0.16, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.AbstractMyMemoryTranslate: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.BelazarTranslate: instructions covered ratio is 0.03, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.AbstractMyMemoryTranslate.1: instructions covered ratio is 0.00, but expected minimum is 0.20
```

**Comment by damien-rembert** [comment]
Works very nicely! 
It's interesting to see that we could enforce different coverage levels for different classes so I guess we could make it mandatory to keep the same level of coverage before and after the PR

**Comment by miurahr** [comment]
> Works very nicely! It's interesting to see that we could enforce different coverage levels for different classes so I guess we could make it mandatory to keep the same level of coverage before and after the PR

Yes, I intend to make it mandatory in CI process in future.
Before that, our community developers will learn work flows, habit to write test, and watch empirical checks for quality assurance.

**Comment by miurahr** [comment]
There are enough coverage on many filters, so when I increase threshold to 60%,  it looks like 

```
 Rule violated for package org.omegat.core.tagvalidation: instructions covered ratio is 0.52, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.xhtml: instructions covered ratio is 0.42, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.openxml: instructions covered ratio is 0.39, but expected minimum is 0.60
  Rule violated for package org.omegat.filters2.text: instructions covered ratio is 0.39, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.flash: instructions covered ratio is 0.52, but expected minimum is 0.60
  Rule violated for package org.omegat.externalfinder: instructions covered ratio is 0.24, but expected minimum is 0.60
  Rule violated for package org.omegat.core.spellchecker: instructions covered ratio is 0.00, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.opendoc: instructions covered ratio is 0.48, but expected minimum is 0.60
  Rule violated for package org.omegat.core.search: instructions covered ratio is 0.38, but expected minimum is 0.60
  Rule violated for package org.omegat.filters2.mozdtd: instructions covered ratio is 0.46, but expected minimum is 0.60
  Rule violated for package org.omegat.core.statistics: instructions covered ratio is 0.50, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.typo3: instructions covered ratio is 0.49, but expected minimum is 0.60
  Rule violated for class org.omegat.core.machinetranslators.Google2Translate: instructions covered ratio is 0.12, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.DeepLTranslate: instructions covered ratio is 0.14, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MyMemoryMachineTranslate: instructions covered ratio is 0.05, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MachineTranslators: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.ApertiumTranslate: instructions covered ratio is 0.10, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MyMemoryHumanTranslate: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.IBMWatsonTranslate: instructions covered ratio is 0.15, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.MicrosoftTranslatorAzure: instructions covered ratio is 0.02, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.BaseTranslate: instructions covered ratio is 0.16, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.AbstractMyMemoryTranslate: instructions covered ratio is 0.00, but expected minimum is 0.20
  Rule violated for class org.omegat.core.machinetranslators.BelazarTranslate: instructions covered ratio is 0.03, but expected minimum is 0.20
  Rule violated for package org.omegat.core.matching: instructions covered ratio is 0.25, but expected minimum is 0.60
  Rule violated for package org.omegat.languagetools: instructions covered ratio is 0.59, but expected minimum is 0.60
  Rule violated for package org.omegat.core.team2.impl: instructions covered ratio is 0.28, but expected minimum is 0.60
  Rule violated for package org.omegat.filters2.text.mozftl: instructions covered ratio is 0.50, but expected minimum is 0.60
  Rule violated for package org.omegat.filters3.xml.xliff: instructions covered ratio is 0.55, but expected minimum is 0.60
  Rule violated for package org.omegat.filters2.moodlephp: instructions covered ratio is 0.47, but expected minimum is 0.60
  Rule violated for package org.omegat.filters2.xtagqxp: instructions covered ratio is 0.06, but expected minimum is 0.60
```

I'd like to merge it with this threshold setting.

**Pull request merged**
