### PR TITLE
docs: Explanation about alternative translations

### PR DESCRIPTION
**Pull request by brandelune**
https://sourceforge.net/p/omegat/mailman/message/37863465/

The text is taken from Marc's How-to.

https://sourceforge.net/p/omegat/documentation/411/

### CODE REVIEW

**Review by Kazephil — COMMENTED** [review]
I've just proposed a slight modification and addition to the explanation.
Have a look!

**Comment by brandelune** [comment]
We need to decide whether we cherry-pick that to 6.0/5.8.

**Comment by Kazephil** [comment]
> We need to decide whether we cherry-pick that to 6.0/5.8.

We probably should.

**Comment by brandelune** [comment]
Please, go ahead :-)

**Comment by Kazephil** [comment]
I'll do it after the fixes from #658 and #659 are merged.

(I guess I could merge them myself. We can simply use the GitHub `Merge pull request` button now, right?

**Comment by miurahr** [comment]
> (I guess I could merge them myself. We can simply use the GitHub `Merge pull request` button now, right?

Yes, you can do it.

**Pull request merged**
