### PR TITLE
Quick fix of NPE

### PR DESCRIPTION
**Pull request by miurahr**
Signed-off-by: Hiroshi Miura <miurahr@linux.com>

### CODE REVIEW

**Comment by amake** [comment]
When can `line` be null? For an empty file?

**Comment by miurahr** [comment]
This is what I got.
```
more omegat14229472552491823969/logs/OmegaT.log
13675: 情報: Git 'clone' 実行開始 (GIT_START)
13675: 情報: Git 'clone' 実行成功 (GIT_FINISH)
13675: 情報: チームモードのプロジェクト用にフォルダー /tmp/teamtest/s2/source が
自動生成されました (CT_AUTOCREATE_DIRECTORY)
13675: 情報: チームモードのプロジェクト用にフォルダー /tmp/teamtest/s2/target が
自動生成されました (CT_AUTOCREATE_DIRECTORY)
13675: 情報: チームモードのプロジェクト用にフォルダー /tmp/teamtest/s2/glossary 
が自動生成されました (CT_AUTOCREATE_DIRECTORY)
13675: 情報: チームモードのプロジェクト用にフォルダー /tmp/teamtest/s2/tm が自動
生成されました (CT_AUTOCREATE_DIRECTORY)
13675: 情報: チームモードのプロジェクト用にフォルダー /tmp/teamtest/s2/dictionar
y が自動生成されました (CT_AUTOCREATE_DIRECTORY)
13675: 情報: Source tokenizer: org.omegat.tokenizer.DefaultTokenizer 
13675: 情報: Target tokenizer: org.omegat.tokenizer.DefaultTokenizer 
13675: 情報: プロジェクト読み込みの開始 (LOG_DATAENGINE_LOAD_START)
13675: FINE: GIT switchToVersion origin/master  
13675: 情報: Load project source files: 2ms 
13675: 情報: リベース開始 (TEAM_REBASE_START)
13675: FINE: Rebase and commit 'omegat/project_save.tmx' 
13675: FINE: GIT switchToVersion origin/master  
13675: FINE: GIT switchToVersion 17deb33c7adbcaf09af318a257d1444f0697a594  
13675: FINE: local file 'omegat/project_save.tmx' doesn't exist 
13675: FINE: GIT switchToVersion origin/master  
13675: 情報: TMX ファイル /tmp/teamtest/s2/.repositories/file_var_tmp_omegat_tes
t.git/omegat/project_save.tmx を読み込み中です (TMXR_INFO_READING_FILE)
13675: 情報: 作成者：OmegaT (TMXR_INFO_CREATION_TOOL)
13675: 情報: バージョン：5.6.0_0_f90cae6f5 (TMXR_INFO_CREATION_TOOL_VERSION)
13675: 情報: 分節化の方法：sentence (TMXR_INFO_SEG_TYPE)
13675: 情報: 原文言語：en (TMXR_INFO_SOURCE_LANG)
13675: 情報: TMX ファイルの読み込みが完了しました (TMXR_INFO_READING_COMPLETE)
13675: FINE: only remote changes - get remote 'omegat/project_save.tmx' 
13675: 情報: TMX ファイル /tmp/teamtest/s2/omegat/project_save.tmx を読み込み中
です (TMXR_INFO_READING_FILE)
13675: 情報: 作成者：OmegaT (TMXR_INFO_CREATION_TOOL)
13675: 情報: バージョン：5.6.0_0_f90cae6f5 (TMXR_INFO_CREATION_TOOL_VERSION)
13675: 情報: 分節化の方法：sentence (TMXR_INFO_SEG_TYPE)
13675: 情報: 原文言語：en (TMXR_INFO_SOURCE_LANG)
13675: 情報: TMX ファイルの読み込みが完了しました (TMXR_INFO_READING_COMPLETE)
13675: FINE: Rebase and commit 'glossary/glossary.txt' 
13675: FINE: GIT switchToVersion origin/master  
13675: FINE: GIT switchToVersion 17deb33c7adbcaf09af318a257d1444f0697a594  
13675: FINE: local file 'glossary/glossary.txt' doesn't exist 
13675: FINE: GIT switchToVersion origin/master  
13675: エラー: 指定したプロジェクトを読み込めませんでした。 (TF_LOAD_ERROR)
13675: エラー: java.lang.NullPointerException 
13675: エラー: 	at org.omegat.util.MagicComment.parse(MagicComment.java:78) 
13675: エラー: 	at org.omegat.gui.glossary.GlossaryReaderTSV.detectEncodingDefau
lt(GlossaryReaderTSV.java:100) 
13675: エラー: 	at org.omegat.gui.glossary.GlossaryReaderTSV.getFileEncoding(Glo
ssaryReaderTSV.java:94) 
13675: エラー: 	at org.omegat.gui.glossary.GlossaryReaderTSV.getFileEncoding(Glo
ssaryReaderTSV.java:86) 
13675: エラー: 	at org.omegat.gui.glossary.GlossaryReaderTSV.read(GlossaryReader
TSV.java:112) 
13675: エラー: 	at org.omegat.core.data.RealProject$2.parseHeadFile(RealProject.
java:1014) 
13675: エラー: 	at org.omegat.core.team2.RebaseAndCommit.rebaseAndCommit(RebaseA
ndCommit.java:145) 
13675: エラー: 	at org.omegat.core.data.RealProject.rebaseAndCommitProject(RealP
roject.java:998) 
13675: エラー: 	at org.omegat.core.data.RealProject.loadProject(RealProject.java
:363) 
13675: エラー: 	at org.omegat.core.data.TestTeamIntegrationChild.main(TestTeamIn
tegrationChild.java:132) 
13675: 情報: プロジェクト読み込みの終了 (LOG_DATAENGINE_LOAD_END)

```

**Comment by amake** [comment]
Hmm. I was hoping to learn *why* it was happening.

Either way, I've applied to `master`. Thanks.

**Comment by miurahr** [comment]
I don't know why but readLine can return null

> readLine
> 
> Returns:
> A String containing the contents of the line, not including any line-termination characters, or null if the end of the stream has been reached
>

**Comment by miurahr** [comment]
I can reproduce with a test case
```
    @SuppressWarnings("serial")
    @Test
    public void testParseEmpty() throws IOException {
        Map<String, String> result = MagicComment.parse(new File("test/data/glossaries/empty.txt"));
        assertEquals(Collections.emptyMap(), result);
    }
```

```

java.lang.NullPointerException
	at org.omegat.util.MagicComment.parse(MagicComment.java:78)
	at org.omegat.util.MagicCommentTest.testParseEmpty(MagicCommentTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

**Comment by amake** [comment]
> I can reproduce with a test case

Great, so that was the cause. We should add that test.

If you still have it locally, could you push it?

**Comment by miurahr** [comment]
> If you still have it locally, could you push it?
 Please see #123

**Comment by amake** [comment]
Thank you!

**Pull request closed without merging**
