### PR TITLE
Bump htmlparse@1.6-20230203

### PR DESCRIPTION
**Pull request by miurahr**

### CODE REVIEW

**Review by kosivantsov — APPROVED** [review]
Everything is fine as far as I can see

**Comment by miurahr** [comment]
@kosivantsov Thank you for the feedback. I'd like to merge it.

**Comment by damien-rembert** [comment]
Nice one, thanks for looking into it!

**Review by damien-rembert — APPROVED** [review]

**Comment by kosivantsov** [comment]
> @kosivantsov Thank you for the feedback. I'd like to merge it.

I would be the last person to ask for advice or agreement in this matter. Everything works as far as I see, but I can't tell you anything about the technical side.

**Comment by miurahr** [comment]
merged into master.

**Pull request closed without merging**
