### PR TITLE
[BUGS#1242] fix Preferences>SaveOptionsPanel - UI of user level post-translate command

### PR DESCRIPTION
**Pull request by miurahr**
SaveOptionsPanel.java was modified without using SaveOptionsPanel.form in NetBeans GUI editor in past commits.

## Pull request type

- Bug fix -> [bug]

## Which ticket is resolved?

- Preference to enable "Project specific External Command" is lost
- https://sourceforge.net/p/omegat/bugs/1242/

## What does this PR change?

- This generates gui source by NetBeans GUI editor and apply similar changes which has applied to SaveOptionsPanel.java
- Affected change; - [RFE#1695] Select output format for statistics output: JSON, XML or Text (#675)

### CODE REVIEW

**Comment by miurahr** [comment]
Before the fix.
image

**Comment by miurahr** [comment]
After the fix.
image

**Review by brandelune — APPROVED** [review]

**Review by Kazephil — APPROVED** [review]
I've made minor tweaks to the UI text, but it looks good otherwise.

**Comment by miurahr** [comment]
Thank you for review and revise of a message. Now I think it is ready for merge.

**Pull request merged**
