### PR TITLE
Dictionary: API for supporting online dictionary (RFE#1597)

### PR DESCRIPTION
**Pull request by miurahr**
Support online dictionary plugins/driver.

1. Introduce registration API for online dictionary; register driver without dictionary file. 

  *  `IDictionaries#addDictionary(IDictionary dictionary)`
  *  `iDictionaries#removeDictionary(IDictionary dictionary)`

2. Introduce query API for parallel bulk query 

  * `IDictionary#retrieveArticles(Collection<String> words)`
  * `IDictionary#retrieveArticlesPredictive(Collection<String> words)`

3. Introduce methods of `DictionariesManager`

  * `DictionariesManager#addOnlineDictionary`
  * `DictionariesManager#removeOnlineDictionary`

4. Refactoring `DictionariesManager` 

  * `DictionariesManager#doLookup` calls the API introduced in No.2: ` result = dict.retrieveArticles(words);`
  * `DictionariesManager#findWords` improved to run in parallel to speed-up on multi-core PC

```java
`        return dicts.parallelStream()
                .map(dict -> doLookUp(dict, queryWords))
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
```

- This resolves RFE#1597

### CODE REVIEW

**Comment by miurahr** [comment]
Here is an experimental implementation how the API is used.

https://github.com/miurahr/omegat-oxford-dictionaries

The plugin query multiple words in threading http session.

**Comment by miurahr** [comment]
It is necessary to test new  APIs.

**Comment by miurahr** [comment]
Test is added.

**Comment by miurahr** [comment]
I believe it is worth and ready for merge.

**Comment by amake** [comment]
Please let me review first

**Comment by miurahr** [comment]
merged as 1098b4f05e2c7f86860ee96fcb4c5288806bf3e4

**Pull request closed without merging**
