### PR TITLE
Updates to Bundle.properties UI strings and to the manual

### PR DESCRIPTION
**Pull request by Kazephil**
[documentation]

## What does this PR change?

- Update some of the Bundle.properties UI strings
- Apply the corresponding changes in the manual
- Improve wording of some explanations in the manual, and fix a few typos.

### CODE REVIEW

**Comment by brandelune** [comment]
It's just the 27e2d632d101c5b231a73a64d0dc2b18a59f3c77 commit that changes unrelated files.
I guess if you revert that commit and then just add the relevant modifications in a new commit, that should do it.

**Comment by Kazephil** [comment]
Just goes to show I shouldn't be trying Git stuff late at night, I guess... :-)

Reverting, removing the files, and committing alone doesn't seem to have taken the extraneous files out of the PR.
Closing and trying again.

**Comment by brandelune** [comment]
Sorry for the bad advice... :(

**Comment by Kazephil** [comment]
No worries. Actually, I think it was my mistake and your suggestion should have worked if I'd done it right.
I think I was on the wrong branch the first time I tried...

**Pull request closed without merging**
