### PR TITLE
Fix duplicated comment display

### PR DESCRIPTION
**Pull request by miurahr**
## Pull request type

- Bug fix

## Which ticket is resolved?

-  GUI: Comment is shown on both Comment and Segment Properties pane
   *  https://sourceforge.net/p/omegat/bugs/1119/

## What does this PR change?

- Show existence flag of comment instead of its content on segment properties pane
- Update flash notifier default keys

### CODE REVIEW

**Comment by miurahr** [comment]
Request for UI/UX feedbacks

**Comment by brandelune** [comment]
Which project did you test it with ?

**Comment by miurahr** [comment]
test project can be get from  https://codeberg.org/miurahr/omegat-test2

Please check `.omegat/omegat.prefs` configuration for test.
```
    <segment_properties_notify_props>hasNote, hasComment</segment_properties_notify_props>
    <notify_notes>true</notify_notes>
    <notify_comments>true</notify_comments>
```

image

**Comment by brandelune** [comment]
The function seems to work, but there is an issue with the file name display. Here is the current master vs. your branch.

Screen Shot 2022-10-08 at 10 02 03

Screen Shot 2022-10-08 at 10 01 35

Your branch sticks to "Instant Start".

**Comment by miurahr** [comment]
I don't touch a code about title and I cannot reproduce it.
> Your branch sticks to "Instant Start".

**Comment by miurahr** [comment]
> The function seems to work, but there is an issue with the file name display. Here is the current master vs. your branch.
>

Please check  Notes, Comments and Segment Properties pane.

**Comment by miurahr** [comment]
Please operation and notifications.

https://user-images.githubusercontent.com/123720/194684747-c1f56ad7-3076-45eb-989f-c1281beddc3a.mp4

**Comment by miurahr** [comment]
> The function seems to work, but there is an issue with the file name display. Here is the current master vs. your branch.
> 
> Your branch sticks to "Instant Start".

Could you provide a detailed instruction to reproduce it,  conditions(mac?, java memory configuration),  and logs when happened?

**Comment by brandelune** [comment]
It is an outstanding bug that has been around for ages and that is most probably not directly related to your code. Aaron and I have investigated it in the past but even when I was able to reproduce it, it was never thoroughly fixed.

**Pull request merged**
