### PR TITLE
Discrepancies between 5.8 UI and manual + review

### PR DESCRIPTION
**Pull request by brandelune**
As I was reviewing the 5.8 FR localization I found a number of discrepancies between the current UI and the manual.
I think they are all fixed here.
I also added a few minor UI review items.

### CODE REVIEW

**Review by miurahr — APPROVED** [review]

**Review by Kazephil — APPROVED** [review]
I've suggested a few wording tweaks. Everything looks good to me.

**Comment by brandelune** [comment]
> I've suggested a few wording tweaks. Everything looks good to me.

Could you do the same for the 6.0 PR, with the exact same content? We need it to move forward with the l10n and the release.

**Comment by Kazephil** [comment]
> > I've suggested a few wording tweaks. Everything looks good to me.
> 
> Could you do the same for the 6.0 PR, with the exact same content? We need it to move forward with the l10n and the release.

I'll get to it (and the 6.1 PR) later this evening.

It might be faster for you to cherry pick those commits into your PRs, though.

**Comment by brandelune** [comment]
> It might be faster for you to cherry pick those commits into your PRs, though.

They're all the same because I've cherry-picked one and applied it to the 2 other branches.

**Comment by Kazephil** [comment]
> > It might be faster for you to cherry pick those commits into your PRs, though.
> 
> They're all the same because I've cherry-picked one and applied it to the 2 other branches.

Exactly. So if you cherry pick my two commits ([22bb540](https://github.com/omegat-org/omegat/pull/585/commits/22bb54044e4b24e940f76bf3fad6eae300bb3f66) and [123a563](https://github.com/omegat-org/omegat/pull/585/commits/123a56361101f27eda97f6b6eda5cc95fcbfe28f)) from your releases/5.8 branch into your releases /6.0 and master branches, we get the same commits in all three branches.

If I copy and paste my changes into the PRs for releases/6.0 and master, we're going to have different commits in each branch for the same modifications.

(Alternatively, I could pull the branches to my fork, cherry pick the commits, and replace your PRs for 6.0 and master with mine.)

**Pull request merged**
