### PR TITLE
Discrepancies between 5.8 UI and manual + review

### PR DESCRIPTION
**Pull request by brandelune**
As I was reviewing the 5.8 FR localization I found a number of discrepancies between the current UI and the manual.
I think they are all fixed here.
I also added a few minor UI review items.

### CODE REVIEW

**Comment by brandelune** [comment]
Why is the code already at 5.8.1?

**Comment by miurahr** [comment]
Is it for master branch? Do you want to apply to releases/5.8 branch?

**Comment by brandelune** [comment]
Sorry. I forgot to close this one.

**Review by brandelune — COMMENTED** [review]
Sorry. I closed this PR and replaced it with a "cleaner" one.

**Comment by miurahr** [comment]
You can edit merge target branch name by clicking "Edit" button in right of title.
image

**Pull request closed without merging**
