### PR TITLE
Simplified Chinese localisation updated to 4.1.5 update 5 (UI)

### PR DESCRIPTION
**Pull request by WynnChen**
Complete Simplified Chinese translation for Bundle_zh_CN.properties. Has been fully tested.

### CODE REVIEW

**Comment by kosivantsov** [comment]
Since this Git repo is mirrored from SVN at SF.net, I'll commit your work to /trunk at SF.net.
The preferred way to localize OmegaT is through the respective OmegaT team project hosted at https://github.com/OmegaT-L10N
I added you as collaborator to https://github.com/OmegaT-L10N/zh_CN, please accept GitHub invitations, and then use this URL to download the team project in OmegaT (no need to fork and make pull requests)

**Comment by WynnChen** [comment]
Thanks for the invitation. I will continue my work there as soon as possible.

**Comment by WynnChen** [comment]
I have synced the translation of Bundle_zh_CN.properties to L10N/zh_CN.

**Comment by WynnChen** [comment]
> 
> 
> Since this Git repo is mirrored from SVN at SF.net, I'll commit your work to /trunk at SF.net.
> The preferred way to localize OmegaT is through the respective OmegaT team project hosted at https://github.com/OmegaT-L10N
> I added you as collaborator to https://github.com/OmegaT-L10N/zh_CN, please accept GitHub invitations, and then use this URL to download the team project in OmegaT (no need to fork and make pull requests)

@kosivantsov I have a question, after I updated the translation, do I need to do "commit taget files" in OmegaT (commit /target directory to the repository)? I noticed that the Chinese L10N content in OmegaT lags far behind the translation in L10N/zh_CN project, so I want to know how the translation result in L10N project integrated into OmegaT?

**Comment by kosivantsov** [comment]
@WynnChen There's no need to commit target files to https://github.com/OmegaT-L10N/zh_CN unless you have a specific reason to do so. When OmegaT L10N manager gets a notification from a team that there are files ready to be used for the next release, the manager opens the respective project locally, compiles the target documents and commits them as needed. So your target documents are not required for management tasks, but if you have use for them for your localisation team, feel free to commit them.

**Pull request closed without merging**
