### PR TITLE
remove messages.xml from the html documentation build process

### PR DESCRIPTION
**Pull request by brandelune**
When the Okapi Filters are enabled the `messages.xml` blocks the loading of the L10n project.

The file is not useful anymore in the web-help build process so I propose that we remove it.

## Which ticket is resolved?

- Remove messages.xml from the build process
   https://sourceforge.net/p/omegat/documentation/381/

## What does this PR change?

- it removes the messages.xml file
- it removes references to it in the html documentation build process (whc-toc.xsl)

## Other information

https://sourceforge.net/p/omegat/mailman/message/37730156/

### CODE REVIEW

**Comment by brandelune** [comment]
> Please add detailed explanation in commit message, and please remove elements instead of comment out.

Is it better now ?

> When we need to be bring back, we can revert commit when you add explanation in commit message.

Indeed. Thank you for the guidance.

**Comment by miurahr** [comment]
> > Please add detailed explanation in commit message, and please remove elements instead of comment out.
> 
> Is it better now ?

To add commit message details in your commit, please do `git rebase -i HEAD~2` command.

1. consolidate two commit into single (s = squash)
2. set "r  = reword" sub command to your commit
3. edit commit message with text editor

You can watch tutorial video for git rebase
https://egghead.io/lessons/git-reword-a-commit-with-git-rebase

**Comment by brandelune** [comment]
Ok. Not the PR title, the commit message... :-) Give me a few minutes.

**Comment by brandelune** [comment]
If I do `git rebase -i HEAD~2` I include 

```
pick c4009c449 Update user guide HTML files (English)
pick 84ced08e5 messages.xml is not useful anymore
```

Is that what you mean ?

**Comment by miurahr** [comment]
```
pick c4009c449 Update user guide HTML files (English)
pick 84ced08e5 messages.xml is not useful anymore

```
if so, change it as follows;

```
pick c4009c449 Update user guide HTML files (English)
r 84ced08e5 messages.xml is not useful anymore
```
and save.
Then Git will launch editor and ask you new message title and body.

**Comment by brandelune** [comment]
I have no understanding of what I am doing, but I followed your instructions. I'm not sure that I managed to do as you requested.

**Comment by brandelune** [comment]
@amake Is there a reason why you closed this without merging ? Is there a problem with this PR ?

**Comment by miurahr** [comment]
This causes an error on manual generation. @brandelune 

see comment
https://github.com/omegat-org/omegat/commit/6e51ff6d074e25249730953c41b64b41cbeb48b2

**Pull request closed without merging**
