### PR TITLE
[BUGS#1225] fix: Bring Issues Panel to front on refresh

### PR DESCRIPTION
**Pull request by miurahr**
This commit introduces a change in the IssuesPanelController where the refreshData function is modified to bring the panel to the forefront each time it refreshes. This adjustment ensure that the refreshed panel remains visible and doesn't get hidden behind main window. Resolved BUGS#1225

## Pull request type

- Bug fix -> [bug]

## Which ticket is resolved?

- List of issues stays hidden in the background
- https://sourceforge.net/p/omegat/bugs/1225/

## What does this PR change?

- `IssuesPanelController#refreshData` does `frame.toFront()`

### CODE REVIEW

**Comment by miurahr** [comment]
I got a behavior to bring window to top when update a issues  check list, but it happened when there is no error but only warnings or there is no issue on the segment.

**Comment by miurahr** [comment]
Changed to raise to front only when updates, found and/or resolved (modified).

**Comment by miurahr** [comment]
i've observed OutOfBound exception
```
04472: エラー: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException 
04472: エラー: 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) 
04472: エラー: 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613) 
04472: エラー: 	at org.omegat.gui.issues.IssuesPanelController$IssueLoader.done(IssuesPanelController.java:600) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) 
04472: エラー: 	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) 
04472: エラー: 	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317) 
04472: エラー: 	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249) 
04472: エラー: 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 
04472: エラー: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) 
04472: エラー: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
04472: エラー: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) 
04472: エラー: 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
04472: エラー: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
04472: エラー: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
04472: エラー: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
04472: エラー: Caused by: java.lang.StringIndexOutOfBoundsException 
04472: エラー: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
04472: エラー: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
04472: エラー: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
04472: エラー: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) 
04472: エラー: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) 
04472: エラー: 	at org.omegat.gui.issues.IssuesPanelController$IssueLoader.doInBackground(IssuesPanelController.java:556) 
04472: エラー: 	at org.omegat.gui.issues.IssuesPanelController$IssueLoader.doInBackground(IssuesPanelController.java:533) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) 
04472: エラー: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
04472: エラー: 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) 
04472: エラー: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
04472: エラー: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
04472: エラー: 	at java.base/java.lang.Thread.run(Thread.java:829) 
04472: エラー: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1 
04472: エラー: 	at java.base/java.lang.String.substring(String.java:1841) 
04472: エラー: 	at org.omegat.gui.glossary.GlossarySearcher.rawMatch(GlossarySearcher.java:153) 
04472: エラー: 	at org.omegat.gui.glossary.GlossarySearcher.lambda$getMatchingTokens$1(GlossarySearcher.java:146) 
04472: エラー: 	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1702) 
04472: エラー: 	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1690) 
04472: エラー: 	at org.omegat.gui.glossary.GlossarySearcher.getMatchingTokens(GlossarySearcher.java:146) 
04472: エラー: 	at org.omegat.gui.glossary.GlossarySearcher.isTokenMatch(GlossarySearcher.java:125) 
04472: エラー: 	at org.omegat.gui.glossary.GlossarySearcher.searchTargetMatches(GlossarySearcher.java:110) 
04472: エラー: 	at org.omegat.gui.glossary.GlossaryManager.searchTargetMatches(GlossaryManager.java:323) 
04472: エラー: 	at org.omegat.gui.issues.TerminologyIssueProvider.lambda$getIssues$0(TerminologyIssueProvider.java:82) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) 
04472: エラー: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) 
04472: エラー: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) 
04472: エラー: 	at org.omegat.gui.issues.TerminologyIssueProvider.getIssues(TerminologyIssueProvider.java:85) 
04472: エラー: 	at org.omegat.gui.issues.IssuesPanelController$IssueLoader.lambda$doInBackground$1(IssuesPanelController.java:555) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) 
04472: エラー: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) 
04472: エラー: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) 
04472: エラー: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) 
04472: エラー: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) 
04472: エラー: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) 
04472: エラー: 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) 
04472: エラー: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) 
04472: エラー: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) 
04472: エラー: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) 
04472: エラー: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327) 
04472: エラー: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) 
04472: エラー: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) 
```

**Comment by miurahr** [comment]
The bug has  already been resolved in #839

**Comment by brandelune** [comment]
Please revert this merge until we find a practical solution to the issue.

The current implementation is extremely annoying for people who work with OmegaT in full screen and need to check issues when leaving a segment.

**Pull request merged**
