### PR TITLE
FR update for 6.0

### PR DESCRIPTION
**Pull request by brandelune**
FR localization update for 6.0

### CODE REVIEW

**Comment by miurahr** [comment]
The PR contains other than update of FR localization.

**Comment by brandelune** [comment]
> The PR contains other than update of FR localization.

I just checked and I don't find files that are not related to the FR localization. Could you tell me what you think should not be there?

**Comment by miurahr** [comment]
When pulling your topic branch to local, I see following two commits. Why?

[discrepencies between UI and manual + UI review](https://github.com/brandelune/omegat/commit/6bd95630a26a4cd2130e30d8ea3a729c06d91997)
[add contributors names](https://github.com/brandelune/omegat/commit/f6bd1b548c801573cb25d330bf3c239914102524)

**Comment by brandelune** [comment]
The commits belong to:
https://github.com/omegat-org/omegat/pull/584/commits
not to this PR.
I don't know why you see them here. There is only one commit in this PR.

**Comment by miurahr** [comment]
https://sourceforge.net/p/omegat/mailman/omegat-development/thread/WX4fk35Cxs9x2jdQQns1gf8582qfgfHxscnwBXdGmc0ZsIVh9QFetuAvNct1untkqW0n329HtwhwKEaBDx3WvxGDLfxKZxTTczNlLEnMSjM%3D%40northside.tokyo/

This is start point to discuss for releases.

and 6.0 is

```
6.0 probably can be released one or two days after (it will only require a minor Java version modification in the manual and a few other places), to stay on the safe side and make sure there are no immediate issues to fix with the 5.8 release.
```

I said the safe side.

**Comment by brandelune** [comment]
> You are using same branch for multiple pull-requests. #584
> 
> You don't follow a project rule to make topic branch named `topic/name/descirption` but use `brandelune:releases/6.0`
> 
> It is a reason why I confused.

Sorry for that. Do you want me to make a separate branch?

**Comment by miurahr** [comment]
> If you have an issue with the calendar, please discuss it on the development list.

Sorry, it is comment that I try to  post on #589.

**Comment by miurahr** [comment]
>  Do you want me to make a separate branch?

No, no need to do it.
Now I understand a situation. I'll rebase and merge on releases/6.0 branch by hand.

**Comment by brandelune** [comment]
> > Do you want me to make a separate branch?
> 
> No, no need to do it. Now I understand a situation. I'll rebase and merge on releases/6.0 branch by hand.

Sorry for adding to your work.

**Comment by miurahr** [comment]
I checked merge behavior in my local, and I want to use merge button on GitHub.

**Review by miurahr — APPROVED** [review]

**Pull request merged**
