### PR TITLE
Update html docs

### PR DESCRIPTION
**Pull request by miurahr**
## Pull request type

- Documentation -> [documentation]

## Which ticket is resolved?

N.A.

## What does this PR change?

- Fix document generation bugs
- Run ./gradlew updateManuals and commits generated docs/

### CODE REVIEW

**Comment by miurahr** [comment]
@brandelune 
This PR includes the fixes for previous breakage of document generation.

**Comment by brandelune** [comment]
No. The introduction.xml is a different file and the Instant Start has been replaced by a "Basic Steps" that comes in a different PR.

I don't know how to make it so that all the PR are deployed one after the other, but that's the case for all the PRs that I have sent.

**Comment by miurahr** [comment]
> No. The introduction.xml is a different file and the Instant Start has been replaced by a "Basic Steps" that comes in a different PR.
> 
> I don't know how to make it so that all the PR are deployed one after the other, but that's the case for all the PRs that I have sent.

Could you mind to tell me "which become what"  and PR, commit, and/or branch  to avoid a misunderstanding.

**Comment by brandelune** [comment]
Thank you. I'll do that later today.

**Comment by brandelune** [comment]
This PR: https://github.com/omegat-org/omegat/pull/376 provides the "Basic Step" item that replaces the Instant Start.

**Comment by miurahr** [comment]
@brandelune  #376 missed

- Update `build.gradle` that refers `<language>/InstantStart.xml` to build up task
- Update all  languages to put `Introduction.xml`

**Comment by brandelune** [comment]
Ok. I'm on it.

**Comment by brandelune** [comment]
I'm working on it and there are a few issues:

Removing all the "instant start" related tasks still builds manuals (even in old versions) but
- languages that only had the instant tutorial end up with nothing
- the current CSS is not working anymore
- for some reason, the global index.html is not created

I'll be trying to fix the CSS and the index issue in the coming days.

Regarding the old instant start, I could create a version that uses the text from the "basic steps" to make sure that we still have something (see https://github.com/omegat-org/omegat/pull/376).

Also, we don't need the l10n tasks anymore. I seem to remember that I'm the one who proposed to have them when I was in charge of L10n, but now that we have all on github, they are irrelevant.

What do you think about all that?

**Comment by miurahr** [comment]
@brandelune 
You need to touch `build.gradle`

**Comment by brandelune** [comment]
Yes. That is what I am doing.

**Comment by brandelune** [comment]
The build process is now fixed with https://github.com/omegat-org/omegat/pull/403. Please review.

**Comment by miurahr** [comment]
No fix. just avoid. 
I'd like to wait #376 finised.

**Comment by miurahr** [comment]
After updated the `doc_src` here will be re-created.

**Comment by Kazephil** [comment]
@miurahr
Has the merge of #376 and #409 fixed this issue?

**Comment by miurahr** [comment]
> @miurahr Has the merge of #376 and #409 fixed this issue?

Yes, the problem is gone now.

**Comment by brandelune** [comment]
Can we close this item?

**Pull request closed without merging**
