### PR TITLE
[5.8][BUGS#1168] feat: error message for loop link

### PR DESCRIPTION
**Pull request by miurahr**
Backport error message enhance from 6.0/6.1

## Pull request type

Please mark github LABEL of the type of change your PR introduces:

- Bug fix -> [bug]

## Which ticket is resolved?

- OmegaT cannot load a project and error dialog with FileSystemLoopException
   * https://sourceforge.net/p/omegat/bugs/1168

## What does this PR change?

- Improve behavior on BUGS#1168 by @miurahr "OmegaT cannot load a project and error dialog with FileSystemLoopException"
- style: Reword new error messages by @kazephil: I rephrased the new error messages a little, and replaced a few unnecessary exclamation marks I happened to notice at the same time. (I thought I'd cleaned them all up a little while back, but I guess I missed a few.)
- style: Update file loop error message by @kazephil: I changed the message again to make it easier to understand for people less familiar with computers.

## Other information

The change here is squashed  changes propoesd in #589

### CODE REVIEW

**Review by Kazephil — COMMENTED** [review]
I prepared a revised error message, but when I tested it, I discovered that (at least on my system) the error dialog does not recognize linebreaks and doesn't display the second (and third lines).

Is there a way to get the dialog to show more lines for the error message? If not, I'll work on a new shorter message that still provides the relevant information.

Also, see additional comments in #577.

**Comment by miurahr** [comment]
I discovered a way to catch the link loop and continue to load  the project in #577 that can be ported to 5.8/6.0 which is compatible with Java 8.

**Comment by miurahr** [comment]
> Is there a way to get the dialog to show more lines for the error message? If not, I'll work on a new shorter message that still provides the relevant information.

#601 is a proposal to show more lines for the error message.

**Comment by miurahr** [comment]
Because this is for error handling and no effect for ordinally feature, I would like to merge now,  and further change wil be come when it is necessary.

**Comment by miurahr** [comment]
Because @kosivantsov asked to freeze a code at https://github.com/omegat-org/omegat/pull/608#issuecomment-1560834199 I think this should be closed without merge.  Isn't it?

**Comment by Kazephil** [comment]
> Because @kosivantsov asked to freeze a code at [#608 (comment)](https://github.com/omegat-org/omegat/pull/608#issuecomment-1560834199) I think this should be closed without merge. Isn't it?

No.

We want to merge #526, #600 and #60, and **_then_** freeze the code so he can make the **_FINAL_** call to update the localization before the release.

Everything else **_must_** wait until 5.8.1/6.0.1 or later.

**Comment by miurahr** [comment]
thanks.

**Pull request merged**
