### PR TITLE
[#1106] CLI: expand tilde(~) in path arguments

### PR DESCRIPTION
**Pull request by miurahr**
This expand tilde(~) character at first character in path argument
into home directory.

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Build and release changes
- [ ] Other (describe below)

## Which ticket is resolved?

- Ticket: [BUG#1106 CLI commands does not expand tilde(~) to home directory](https://sourceforge.net/p/omegat/bugs/1106/)

## discussed in dev ML.

- Link: https://sourceforge.net/p/omegat/mailman/omegat-development/thread/6581ad52-c5ef-4dc4-f5db-224bf65a8ef6%40northside.tokyo/#msg37693581
- Title: [[OmTdev] CLI path resolver (Was: CLI mode for stats)](https://sourceforge.net/p/omegat/mailman/message/37693581/)

## What does this PR change?

- Expand tilde(~) character in path related arguments;
  - config-dir
  - config-file
  - bundle
  - project path
  - alignDir
  
## Other information

related to PR #235

### CODE REVIEW

**Comment by miurahr** [comment]
From bash manual description, implementation is uncompleted.

https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

> 3.5.2 Tilde Expansion
If a word begins with an unquoted tilde character (‘~’), all of the characters up to the first unquoted slash (or all characters, if there is no unquoted slash) are considered a tilde-prefix. If none of the characters in the tilde-prefix are quoted, the characters in the tilde-prefix following the tilde are treated as a possible login name. If this login name is the null string, the tilde is replaced with the value of the HOME shell variable. If HOME is unset, the home directory of the user executing the shell is substituted instead. Otherwise, the tilde-prefix is replaced with the home directory associated with the specified login name.
>
> If the tilde-prefix is ``‘~+’``, the value of the shell variable ``PWD`` replaces the tilde-prefix. If the tilde-prefix is ``‘~-’``, the value of the shell variable ``OLDPWD``, if it is set, is substituted.

**Comment by miurahr** [comment]
> From bash manual description, implementation is uncompleted.
> 
> https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html
> 
> > 3.5.2 Tilde Expansion
> > If a word begins with an unquoted tilde character (‘~’), all of the characters up to the first unquoted slash (or all characters, if there is no unquoted slash) are considered a tilde-prefix. If none of the characters in the tilde-prefix are quoted, the characters in the tilde-prefix following the tilde are treated as a possible login name. If this login name is the null string, the tilde is replaced with the value of the HOME shell variable. If HOME is unset, the home directory of the user executing the shell is substituted instead. Otherwise, the tilde-prefix is replaced with the home directory associated with the specified login name.
> > If the tilde-prefix is `‘~+’`, the value of the shell variable `PWD` replaces the tilde-prefix. If the tilde-prefix is `‘~-’`, the value of the shell variable `OLDPWD`, if it is set, is substituted.

Now handles ``~+`` , ``~-`` and ``~`` in argument paths.
Ready for merge.

**Comment by miurahr** [comment]
merged to master.

**Comment by brandelune** [comment]
As I wrote yesterday, the current code still does not seem to expand the tilde. The error message is different though.

Failure with:

50097: Info: Project loading end (LOG_DATAENGINE_LOAD_END)
50097: Info: Got directory/file open error. Does specified directory exist? 
50097: Info: Project closed (LOG_DATAENGINE_CLOSE)

**Comment by miurahr** [comment]
@brandelune which current code? does your tested codes HEAD hash?

**Comment by miurahr** [comment]
9a75dc5 don't have this fix.

**Pull request closed without merging**
