### PR TITLE
Move the "shortcut based workflow" to the introduction

### PR DESCRIPTION
**Pull request by brandelune**
I move the section to the introduction to make sure that it gets more views.

I also changed it to the 2nd person.

### CODE REVIEW

**Comment by miurahr** [comment]
lgtm.

**Review by Kazephil — COMMENTED** [review]
@brandelune 
I tried editing the file directly to make changes this time around. Have a look and see if that works better.

**Comment by brandelune** [comment]
You forgot a period that I just added. Can you confirm?

**Review by Kazephil — APPROVED** [review]
Nice catch!

**Comment by miurahr** [comment]
I've merged into `master` after rebase.

**Pull request closed without merging**
