### PR TITLE
Expose slf4j and vldocking for plugin projects

### PR DESCRIPTION
**Pull request by miurahr**
It is better to expose slf4j-api and vldocking for plugin projects.

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

### CODE REVIEW

**Comment by miurahr** [comment]
Gradle [manual](https://docs.gradle.org/current/userguide/java_library_plugin.html) said we should use 'api' instead of 'compile' which flagged as deprecation,  but it does not work for my environment, and I don't know why now, so I uses 'compile'.

**Comment by amake** [comment]
What was your issue using `api` and how can I reproduce it?

**Comment by amake** [comment]
Also can you link me to an example of a project that shows the problem you're hoping to fix with this change?

**Comment by miurahr** [comment]
> Also can you link me to an example of a project that shows the problem you're hoping to fix with this change?

`gradle-omegat-plugin` project  is to support plugin development, and the code here is
insert vldocking as a plugin dependency.
https://github.com/miurahr/gradle-omegat-plugin/blob/master/src/main/kotlin/org/omegat/gradle/Setup.kt#L64
https://github.com/miurahr/gradle-omegat-plugin/blob/master/src/main/kotlin/org/omegat/gradle/config/DefaultModule.kt#L20

`omegat-textra-plugin` project use slf4j for logging because OmegaT use it.
Because  slf4j version is not exposed from OmegaT , the project need to add its dependency explicitly.
https://github.com/miurahr/omegat-textra-plugin/blob/master/build.gradle.kts#L28

`omegat-browser` project depends on vldocking and put it explicitly.
https://github.com/yoursdearboy/omegat-browser/blob/master/build.gradle

**Comment by miurahr** [comment]
When changing  Line 109 of `build.gradle` to `api`  I got gradle error as follows,

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/miurahr/Projects/omegat/build.gradle' line: 109
> 
> * What went wrong:
> A problem occurred evaluating root project 'OmegaT'.
> > Could not find method api() for arguments [org.slf4j:slf4j-api:1.7.25] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

This error seems that I missed to add  plugin ` id 'java-library'` that support `api`

**Comment by amake** [comment]
Thanks for figuring out the `java-library` thing. My only remaining concern is that the contents of the distfiles are not changed by adding `java-library`.

I plan to diff before and after the change to make sure, but if you have time to check yourself please let me know the results.

**Comment by miurahr** [comment]
```
$ diff -ur a b
diff -ur a/META-INF/MANIFEST.MF b/META-INF/MANIFEST.MF
--- a/META-INF/MANIFEST.MF	2021-01-31 16:18:32.000000000 +0900
+++ b/META-INF/MANIFEST.MF	2021-01-31 16:14:46.000000000 +0900
@@ -9,35 +9,35 @@
  glossary.taas.TaaSPlugin org.omegat.externalfinder.ExternalFinder
 OmegaT-Plugin: true
 Main-Class: org.omegat.Main
-Class-Path: lib/commons-io-2.7.jar lib/language-all-3.5.jar lib/language
- -en-3.5.jar lib/language-fa-3.5.jar lib/language-fr-3.5.jar lib/languag
- e-de-DE-x-simple-language-3.5.jar lib/language-de-3.5.jar lib/language-
- pl-3.5.jar lib/language-ca-3.5.jar lib/language-it-3.5.jar lib/language
- -br-3.5.jar lib/language-nl-3.5.jar lib/language-pt-3.5.jar lib/languag
- e-ru-3.5.jar lib/language-ast-3.5.jar lib/language-be-3.5.jar lib/langu
- age-zh-3.5.jar lib/language-da-3.5.jar lib/language-eo-3.5.jar lib/lang
- uage-gl-3.5.jar lib/language-el-3.5.jar lib/language-is-3.5.jar lib/lan
- guage-ja-3.5.jar lib/language-km-3.5.jar lib/language-lt-3.5.jar lib/la
- nguage-ml-3.5.jar lib/language-ro-3.5.jar lib/language-sk-3.5.jar lib/l
- anguage-sl-3.5.jar lib/language-es-3.5.jar lib/language-sv-3.5.jar lib/
- language-ta-3.5.jar lib/language-tl-3.5.jar lib/language-uk-3.5.jar lib
- /languagetool-core-3.5.jar lib/ictclas4j-1.0.1.jar lib/commons-lang-2.6
- .jar lib/slf4j-jdk14-1.7.25.jar lib/desktopsupport-0.3.0.jar lib/jaxb-a
- pi-2.3.1.jar lib/jaxb-core-2.3.0.1.jar lib/jaxb-impl-2.3.2.jar lib/pdfb
- ox-2.0.21.jar lib/maligna-3.0.0.jar lib/dictzip-lib-0.9.1.jar lib/trie4
- j-0.9.8.jar lib/juniversalchardet-2.3.2.jar lib/vldocking-3.0.5.jar lib
- /htmlparser-1.5.jar lib/gnudiff4j-1.15.jar lib/lib-mnemonics-1.0.jar li
- b/jmyspell-core-1.0.0-beta-2.jar lib/lucene-core-5.2.1-1.jar lib/lucene
- -analyzers-kuromoji-5.2.1.jar lib/lucene-analyzers-smartcn-5.2.1.jar li
- b/lucene-analyzers-stempel-5.2.1.jar lib/lucene-analyzers-common-5.2.1.
- jar lib/org.eclipse.jgit-4.11.8.201904181247-r.jar lib/jsch.agentproxy.
- jsch-0.0.9.jar lib/svnkit-1.8.14.jar lib/jsch.agentproxy.connector-fact
- ory-0.0.9.jar lib/jsch.agentproxy.svnkit-trilead-ssh2-0.0.9.jar lib/sup
- ertmxmerge-2.0.1.jar lib/jasypt-1.9.3.jar lib/rstaui-3.0.4.jar lib/lang
- uagesupport-3.0.2.jar lib/autocomplete-3.0.5.jar lib/rsyntaxtextarea-3.
- 0.8.jar lib/xmlrpc-client-3.1.3.jar lib/lucene-gosen-5.0.0-ipadic.jar l
- ib/hunspell-native-libs-2.9.jar lib/groovy-dateutil-3.0.5.jar lib/ivy-2
- .5.0.jar lib/language-detector-0.5.jar lib/slf4j-api-1.7.25.jar lib/jav
+Class-Path: lib/vldocking-3.0.5.jar lib/slf4j-jdk14-1.7.25.jar lib/org.e
+ clipse.jgit-4.11.8.201904181247-r.jar lib/language-all-3.5.jar lib/lang
+ uage-en-3.5.jar lib/language-fa-3.5.jar lib/language-fr-3.5.jar lib/lan
+ guage-de-DE-x-simple-language-3.5.jar lib/language-de-3.5.jar lib/langu
+ age-pl-3.5.jar lib/language-ca-3.5.jar lib/language-it-3.5.jar lib/lang
+ uage-br-3.5.jar lib/language-nl-3.5.jar lib/language-pt-3.5.jar lib/lan
+ guage-ru-3.5.jar lib/language-ast-3.5.jar lib/language-be-3.5.jar lib/l
+ anguage-zh-3.5.jar lib/language-da-3.5.jar lib/language-eo-3.5.jar lib/
+ language-gl-3.5.jar lib/language-el-3.5.jar lib/language-is-3.5.jar lib
+ /language-ja-3.5.jar lib/language-km-3.5.jar lib/language-lt-3.5.jar li
+ b/language-ml-3.5.jar lib/language-ro-3.5.jar lib/language-sk-3.5.jar l
+ ib/language-sl-3.5.jar lib/language-es-3.5.jar lib/language-sv-3.5.jar 
+ lib/language-ta-3.5.jar lib/language-tl-3.5.jar lib/language-uk-3.5.jar
+  lib/languagetool-core-3.5.jar lib/language-detector-0.5.jar lib/slf4j-
+ api-1.7.25.jar lib/jaxb-api-2.3.1.jar lib/commons-io-2.7.jar lib/ictcla
+ s4j-1.0.1.jar lib/commons-lang-2.6.jar lib/desktopsupport-0.3.0.jar lib
+ /jaxb-core-2.3.0.1.jar lib/jaxb-impl-2.3.2.jar lib/pdfbox-2.0.21.jar li
+ b/maligna-3.0.0.jar lib/dictzip-lib-0.9.1.jar lib/trie4j-0.9.8.jar lib/
+ juniversalchardet-2.3.2.jar lib/htmlparser-1.5.jar lib/gnudiff4j-1.15.j
+ ar lib/lib-mnemonics-1.0.jar lib/jmyspell-core-1.0.0-beta-2.jar lib/luc
+ ene-core-5.2.1-1.jar lib/lucene-analyzers-kuromoji-5.2.1.jar lib/lucene
+ -analyzers-smartcn-5.2.1.jar lib/lucene-analyzers-stempel-5.2.1.jar lib
+ /lucene-analyzers-common-5.2.1.jar lib/jsch.agentproxy.jsch-0.0.9.jar l
+ ib/svnkit-1.8.14.jar lib/jsch.agentproxy.connector-factory-0.0.9.jar li
+ b/jsch.agentproxy.svnkit-trilead-ssh2-0.0.9.jar lib/supertmxmerge-2.0.1
+ .jar lib/jasypt-1.9.3.jar lib/rstaui-3.0.4.jar lib/languagesupport-3.0.
+ 2.jar lib/autocomplete-3.0.5.jar lib/rsyntaxtextarea-3.0.8.jar lib/xmlr
+ pc-client-3.1.3.jar lib/lucene-gosen-5.0.0-ipadic.jar lib/hunspell-nati
+ ve-libs-2.9.jar lib/groovy-dateutil-3.0.5.jar lib/ivy-2.5.0.jar lib/jav
  ax.activation-api-1.2.0.jar lib/fontbox-2.0.21.jar lib/segment-2.0.0.ja
  r lib/httpclient-4.5.2.jar lib/commons-logging-1.2.jar lib/jsch.agentpr
  oxy.usocket-jna-0.0.9.jar lib/jsch.agentproxy.pageant-0.0.9.jar lib/jna
diff -ur a/org/omegat/Version.properties b/org/omegat/Version.properties
--- a/org/omegat/Version.properties	2021-01-31 16:18:30.000000000 +0900
+++ b/org/omegat/Version.properties	2021-01-31 16:14:46.000000000 +0900
@@ -1,4 +1,4 @@
-#Sun, 31 Jan 2021 16:18:31 +0900
+#Sun, 31 Jan 2021 16:14:46 +0900
 #/**************************************************************************
 # OmegaT - Computer Assisted Translation (CAT) tool
 #          with fuzzy matching, translation memory, keyword search,
@@ -38,7 +38,7 @@
 # Update is deprecated; do not use any value other than zero.
 update=0
 # Revision is managed by tooling; do not adjust manually
-revision=4470bbb50
+revision=b959cf53d
 # Use an empty string for non-beta versions (Standard flavor) and "_Beta" for
 # beta versions (Latest flavor)

```

**Comment by miurahr** [comment]
Difference is just a sort order of Class-Path properties, and all classes and resources are identical.

**Comment by amake** [comment]
Thanks for doing that. I also checked a full `./gradlew installMacDist` and the only difference was in `OmegaT.jar`.

I've squashed and committed to `master` on SourceForge.

**Pull request closed without merging**
