### PR TITLE
feat: Introduce "Tip of the DAY" startup dialog and subproject modules feature

### PR DESCRIPTION
**Pull request by miurahr**
Introduce "Tip of the Day" dialog on startup.

## Pull request type

- Feature enhancement -> [enhancement]

## Which ticket is resolved?

- Tip of the Day, displayed at start
  * https://sourceforge.net/p/omegat/feature-requests/512/

## What does this PR change?

- Add dependency "tokyo.northside:tipoftheday:0.3.0"
- Add feature "Tip of the Day"
- Add the "Tip of the Day"  menu item in help menu
- Contents sould be stored under  "docs/<lang>/tips/"
- Contents can use simple HTML5 and subset of CSS.

### Where to add texts for "Tip of the Day"?

``<project root>/tipoftheday/docs/tips/<lang>/*.html``

### TODO:

- [x]  Translations of UI labels
- [x] More tips texts
- [x]  Localizations of tips
- [x] Add development note in docs_devel

### CODE REVIEW

**Comment by amake** [comment]
I'm sorry, I won't be able to review this.

**Comment by miurahr** [comment]
Now commits history is re-created  for the review and be easy to maintain.

**Comment by miurahr** [comment]
1.  a7322c2  allows plugins insert menu item into help menu tree 
2.  20f3ca6  support "modules" folder in installation and development environment
3.  bf6af69  just a sytle change of build.gradle file; move allprojects block early place
4.  27a5cce update build.gradle that put common settings in allprojects block
5.  f2ae45b Introduce "tip of the day" subproject as a core plugin module.

**Comment by miurahr** [comment]
I think it is ready to merge.
Further additions  and translations of contents will be happen in another PR.

**Pull request merged**
