### PR TITLE
Update user guide HTML files (English)

### PR DESCRIPTION
**Pull request by miurahr**

### CODE REVIEW

**Comment by brandelune** [comment]
It looks fin here.

**Comment by brandelune** [comment]
But we need to remove the DRAFT flag from the docbook.

**Comment by miurahr** [comment]
> But we need to remove the DRAFT flag from the docbook.

Could you please propose to fix it?

**Comment by brandelune** [comment]
It's ok. But there is a problem that comes from the HTML. Some IDs are not defined and create artificial diffs.

So, let's fix the XML first and rebuild the files. Is that OK with you? If yes, I'll handle the XML.

**Comment by miurahr** [comment]
> It's ok. But there is a problem that comes from the HTML. Some IDs are not defined and create artificial diffs.
> 
> So, let's fix the XML first and rebuild the files. Is that OK with you? If yes, I'll handle the XML.

Please.

**Comment by brandelune** [comment]
done in a separate PR.

**Pull request merged**
