### PR TITLE
Refactor tmx entry part2

### PR DESCRIPTION
**Pull request by t-cordonnier**
This Pull Request is continuation of #185 

The role of these patches is to solve concerns mentioned by @miurahr about the role of PrepareTMXEntry class
This is of course one possible solution, not exclusive.

While patches from #185 were here for ensure plugins compatibility even in case of later changes inside OmegaT, the last patches here are known to break backward compatibility (see https://sourceforge.net/p/omegat/mailman/message/37593315/)
For that reason this pull request remains as a draft.

### CODE REVIEW

**Comment by miurahr** [comment]
Progress?

**Comment by t-cordonnier** [comment]
No, I do not work on this right now. I had divided my work in two PR, last time, precisely to have the possibility to postpone this second part.

**Comment by brandelune** [comment]
@t-cordonnier Was the first part that you mention merged?

**Comment by brandelune** [comment]
Do we set a milestone here ?

**Comment by miurahr** [comment]
No need.

**Comment by miurahr** [comment]
stalled.

**Pull request closed without merging**
