### PR TITLE
docgen: Specify uid:gid for docker run

### PR DESCRIPTION
**Pull request by miurahr**
When generating docs from gradle task, it failed with permission error on linux envionment.
This change solved the problem.

## Pull request type

Please check the type of change your PR introduces:

- [x] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Build and release changes
- [ ] Other (describe below)

## Which ticket is resolved?

- Link: https://sourceforge.net/p/omegat/bugs/1112/ 
- Title:  doc_src/docgen docker container should handle UID/GID properly

## What does this PR change?

- Update doc_src/docgen : add docker command option -u with host users uid:gid

### CODE REVIEW

**Comment by miurahr** [comment]
I am afraid whether it also work on macos

**Comment by brandelune** [comment]
I can't tell because I don't use Docker to build the docs. I use the "manual" install documented in the Readme.md.

I think @kosivantsov uses Linux and he might use Docker to generate the doc. Maybe he is in a better position to check your modification.

**Comment by miurahr** [comment]
I use Linux and test with `gradlew manualHtmlEn` task that is fine.
I'd like to merge it and ask other translators or writers (if any) on Nightly version.

**Comment by miurahr** [comment]
merged as 75cc2bc31cbd4

**Pull request closed without merging**
