### PR TITLE
Topic/jc/issues foundin l10 n process

### PR DESCRIPTION
**Pull request by brandelune**
This is a list of typos and other issues found during the l10n process by @kosivantsov and his team.

### CODE REVIEW

**Comment by miurahr** [comment]
@brandelune  please rebase to master, resolve conflict then, force push to your github repositlry?

**Comment by brandelune** [comment]
> @brandelune please rebase to master, resolve conflict then, squash commits, and force push to your github repositlry?

I'll do. There must be something I'm doing wrong because on my local merges with upstream/master...

**Comment by brandelune** [comment]
I'm not sure if what I did is correct. Can you check @miurahr ?

**Comment by miurahr** [comment]
> I'm not sure if what I did is correct. 

Could you read this article? This is what I asked.
https://hackernoon.com/how-to-use-git-rebase-to-squash-a-sequence-of-commits-to-a-new-base-commit-wf6c3522

**Comment by brandelune** [comment]
Ok. This one is much clearer. I'll try later this week.

**Comment by brandelune** [comment]
I'll be working on that today. Thank you !

**Comment by brandelune** [comment]
I think I made it :-)

**Comment by brandelune** [comment]
> Could you read this article? This is what I asked. https://hackernoon.com/how-to-use-git-rebase-to-squash-a-sequence-of-commits-to-a-new-base-commit-wf6c3522

@Kazephil check those tutorials for your recent commits.

`git rebase -i Head~8`
(to get the last 8 commits)

You enter a VI interface where you mark the first commit as a "pick" and where you replace the 7 other "pick" by "s" for squash.

Then you :wq!

Then git proposes a VI interface to edit the commit message. Edit and write-quit

Then 

`git push --force`

to rewrite the remote contents.

**Pull request merged**
