### PR TITLE
Updates to command line launch section of manual.

### PR DESCRIPTION
**Pull request by Kazephil**
## Pull request type
[documentation]

## What does this PR change?

- Improve wording and fix incomplete sentences.
- Unify use of "parameters" vs. "options": Java parameters, OmegaT options.

### CODE REVIEW

**Comment by miurahr** [comment]
merged onto sourceforge's master again as 21841a0e

**Comment by Kazephil** [comment]
Thank you!
It looks like a few other commits in PRs that were accepted did not make it to the Sourceforge master correctly.
Would it be easier if I just sent a new PR with those commits?

**Comment by miurahr** [comment]
> Thank you! It looks like a few other commits in PRs that were accepted did not make it to the Sourceforge master correctly. Would it be easier if I just sent a new PR with those commits?

Yes, it is little bit frustrating task so you are welcome to make new PR for that. Could you please rebase on master for each PR?

@Kazephil

**Comment by Kazephil** [comment]
@miurahr 
OK. I've just sent a new PR (#342) from a branch created off my master branch (that already contained the commits from the GitHub official mirror master before Sourceforge synchronization overwrote them).

I'll make sure future PRs use branches rebased on master. Thanks!

**Pull request merged**
