### PR TITLE
Add new ex. to fuzzy matches and new explanation to 3rd percentage

### PR DESCRIPTION
**Pull request by brandelune**
Documentation issue:
https://github.com/omegat-org/omegat/issues/475

Related to PR:
https://github.com/omegat-org/omegat/pull/467

### CODE REVIEW

**Comment by brandelune** [comment]
I've changed the line according to Briac's description. Although not directly related to this change (but related to the fuzzy pane) I added a second fuzzy match to the example and modified the CSS accordingly.

**Comment by Kazephil** [comment]
@brandelune 
Looks good to me. I think we also need a note in the description of the minimum threshold to add the [information provided by Briac](https://github.com/omegat-org/omegat/pull/467#issuecomment-1427039197).

I just sent a PR for that to your fork.

**Comment by brandelune** [comment]
> @brandelune Looks good to me. I think we also need a note in the description of the minimum threshold to add the [information provided by Briac](https://github.com/omegat-org/omegat/pull/467#issuecomment-1427039197).
> 
> I just sent a PR for that to your fork.

I don't think the extra info is required since it should have been like this from the beginning and people did not expect it to not work that way (hence the bug report). I don't think we should add info related to bug fixes in the manual :-)

**Review by miurahr — APPROVED** [review]

**Review by Kazephil — APPROVED** [review]

**Comment by miurahr** [comment]
rebased and merged into master.

**Pull request closed without merging**
