### PR TITLE
[RFE#1271] feat: provide  linux standard packages

### PR DESCRIPTION
**Pull request by miurahr**
## Pull request type

- Build and release changes -> [build/release]

## Which ticket is resolved?

- #1721 Provide package "deb" and "rpm" as distribution format for linux
- https://sourceforge.net/p/omegat/feature-requests/1721/

## What does this PR change?

- Add gradle jpackage plugin
- Add task linuxDebDist and linuxRpmDist
- produce debian and rpm package.

## Other information

- discussed in [dev-ml](https://sourceforge.net/p/omegat/mailman/omegat-development/thread/zmuMdSRyYxr_rUZWYLNakRIHNiS71-ks7ww2LuUvQSCQPda1YdUqgVRLFdjFHxltgYQwGXGunV0FFuV3dNkqQDgN54HRIDN4qGrqPstE69s%3D%40northside.tokyo/#msg46693967)

- jpackage tool bundles JRE from a  java runtime which gradle run on. Because Azure pipelines CI environment uses Ubuntu 22.04, it bundles runtime from ubuntu package openjdk-17-jdk 17.0.8+1 version.

### CODE REVIEW

**Comment by miurahr** [comment]
@damien-rembert could you test a generated package on your environment?

**Comment by miurahr** [comment]
TODO:

- [ ] add a note on developer document

**Comment by damien-rembert** [comment]
@miurahr I will give it a go this weekend :)

**Comment by miurahr** [comment]
@Kazephil  @brandelune 
I've update developers manual to describe packaging in details.
Could you review document?

**Comment by Kazephil** [comment]
> @Kazephil @brandelune I've update developers manual to describe packaging in details. Could you review document?

Give me a few days.

**Comment by damien-rembert** [comment]
Very nice.
I created and installed locally a deb package, everything worked as expected.
This was on KDE Neon 5.27

**Review by damien-rembert — APPROVED** [review]

**Pull request merged**
