### PR TITLE
Support markUnknown feature of Apertium

### PR DESCRIPTION
**Pull request by unhammer**
Untested! I'd like to add support for markUnknown, but I get this error when building:
```
$ /snap/bin/gradle assembleDist

Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/me/src/omegat/build.gradle' line: 10

* What went wrong:
Plugin [id: 'com.github.spotbugs', version: '4.7.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.spotbugs:com.github.spotbugs.gradle.plugin:4.7.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
```

@MarcRiera I based it off your PR https://github.com/omegat-org/omegat/pull/37 you may be interested in this too

### CODE REVIEW

**Comment by amake** [comment]
> * What went wrong:
> Plugin [id: 'com.github.spotbugs', version: '4.7.0'] was not found in any of the following sources:

Weird. My machine and [CI](https://dev.azure.com/omegat-org/OmegaT/_build/results?buildId=2396&view=results) have no problem resolving `com.github.spotbugs` 4.7.0.

The only thing I can see is

> `$ /snap/bin/gradle assembleDist`

You're using some system Gradle that is different from our wrapper. I had no problems with my system Gradle which is also 6.8.3, but just to remove one variable please try invoking `./gradlew` instead.

**Comment by unhammer** [comment]
Ooh `./` – I thought `gradlew` was a command :see_no_evil:  maybe https://omegat.sourceforge.io/manual-latest/en/chapter.installing.and.running.html#building.OmegaT.from.source should include the `./` before `gradlew`.

Now I'm able to test and it seems to work for me :) The only issue is that translations seem to be cached (so if I turn on the switch after translating something, I the unknown words aren't retranslated with marking when I click the segment again), but I suppose it's not a big problem since people will not tend to turn it on and off in the same session.

**Comment by amake** [comment]
> (maybe https://omegat.sourceforge.io/manual-latest/en/chapter.installing.and.running.html#building.OmegaT.from.source should include the `./` before `gradlew`)

It doesn't work on Windows then, so I guess we just need to be super verbose and list both patterns.

**Comment by MarcRiera** [comment]
Tested, works as expected!

@unhammer Regarding the caching issue: there's a method that could be used to fix it (clearCache, see here: https://omegat.sourceforge.io/javadoc-latest/org/omegat/core/machinetranslators/BaseTranslate.html#clearCache--). As far as I know, the caching is used to prevent duplicate requests, which is important for MT plugins for services with word/request limits. Given that it is now possible to connect to third-party or local Apertium API services, clearing the cache without the user knowing about it could lead to unexpected behaviour if someone ever builds a limited service based on the Apertium API.

As you have already pointed out, turning this on and off in the middle of a translation session should be rare, so I wouldn't change anything else. Maybe a generic note about caching could be added in the MT section of OmegaT's user guide (because this is not limited to Apertium).

**Comment by unhammer** [comment]
@amake Does this seem mergable? Anything more you need from me?

**Comment by amake** [comment]
Sorry, I haven't had time to review it yet. I will let you know.

**Comment by amake** [comment]
Thanks for your contribution! I have committed to `master` with minor changes.

Documented here: https://sourceforge.net/p/omegat/feature-requests/1563/

Upstream will be synced to GitHub shortly.

**Comment by unhammer** [comment]
Thank you! :-)

**Pull request closed without merging**
