### PR TITLE
feat: Improve spell checker: use dict bundled in LT, drop jmyspell, and add morfologik

### PR DESCRIPTION
**Pull request by miurahr**
LanguageTool now uses Morfologik as a spell checker engine, and bundles morfologik dictionary.
This improvement support Morfologik spell checker in OmegaT module.

When you run OmegaT on a project that target language is en_AU then you will find you can check spells
with a LT internal dictionary en_AU.dict that is automatically appears in users spell dictionary dir.

## Pull request type

- Feature enhancement -> [enhancement]

## Which ticket is resolved?

- Support Morfologik spell checker and use LT bundled dictionary
- https://sourceforge.net/p/omegat/feature-requests/1748/

## What does this PR change?

- Add dependency for morfologik-speller
- Drop dependency for jmyspell-core
- Refactoring to produce hunspell-spellchecker and morfologik-spellchecker module

## Other information

- [x] Unit tests

### CODE REVIEW

**Review by brandelune — APPROVED** [review]

**Comment by miurahr** [comment]
There is unrelated coding style fixes in ` OConsts` and several unwanted copyright header changes. We still have TODO to make Unit test for the features.

**Comment by miurahr** [comment]
Rebased on master and recreate commits for review.

**Comment by miurahr** [comment]
Now unit tests are added, then fix several issues.

**Comment by miurahr** [comment]
image

Configuration screen is as same as OmegaT 5.8/6.0

but It can handle both Hunspell and Morfologik dictionary;  de_DE is Hunspell,  en-GB is Morfologik
```bash
~/.omegat/spelling$ ls -l
-rw-rw-r-- 1 miurahr miurahr   19214  5月 26 16:23 de_DE.aff
-rw-rw-r-- 1 miurahr miurahr 4868438  5月 26 16:23 de_DE.dic
-rw-rw-r-- 1 miurahr miurahr  718340  5月 26 16:27 en_GB.dict
-rw-rw-r-- 1 miurahr miurahr     506  5月 26 16:27 en_GB.info
```

and en_GB files are copied from LT.

**Comment by miurahr** [comment]
Unit test cases passed

- [ ] Hunspell to check spelling with pre-installd dictionary. 
- [x] Hunspell to check spelling with Bundled fr-FR dictionary.
- [x] Hunspell to check spelling with LT bundled  de-DE dictionary.
- [x] Morfologik to check spelling with pre-installed de-DE dictionary.
- [x] Morfologik to check spelling with LT bundled en-AU dictionary

**Pull request merged**
