### PR TITLE
chore: allow UTF-8 character as source file

### PR DESCRIPTION
**Pull request by miurahr**
- Allow UTF-8 character for comments, especially for author name

## Pull request type

- Build and release changes -> [build/release]
- Other (describe below)

## What does this PR change?

- Add compiler flag to allow UTF-8 in java source files
- Update test case not to check US-ASCII
- A check should be done by spotless and checkstyle, instead of crafted one

### Related topic:  UTF-8 in Bundle.properties

Here is a Dev-ML discussion thread about BUNDLE file.

https://sourceforge.net/p/omegat/mailman/omegat-development/thread/8zfUNKLS058FYMIUPADGzNmrOOu_73IQWvrNRLFGTbfPmZke8l6fR9yAtLT2j1cGOo6ZpeQ4j-hNbT8fNAfgAtaEb2kmScQffrmXhGtZmx4%3D%40northside.tokyo/#msg37844491

### CODE REVIEW

**Review by brandelune — APPROVED** [review]
Thank you for that. It will make l10n easier.
Please refer to the dev list comments for when to implement the changes.

**Comment by miurahr** [comment]
> Thank you for that. It will make l10n easier. Please refer to the dev list comments for when to implement the changes.

This is not one I proposed in dev list, that is against `BUNDLE`

This is against `*.java` file. I proposed it to allow @briacp name e-accute in java source file comment.

**Comment by miurahr** [comment]
> > Thank you for that. It will make l10n easier. Please refer to the dev list comments for when to implement the changes.
> 
> This is not one I proposed in dev list, that is against `BUNDLE`
> 
> This is against `*.java` file. I proposed it to allow @briacp name e-accute in java source file comment.

Sorry I pasted a dev list link about BUNDLE discussion. It is my mistake.

**Comment by brandelune** [comment]
> Sorry I pasted a dev list link about BUNDLE discussion. It is my mistake.

No problem at all.

**Review by briacp — COMMENTED** [review]
👍
Thanks Hiroshi

**Pull request merged**
