### PR TITLE
index.xml is a generated file, it should not be commited

### PR DESCRIPTION
**Pull request by brandelune**
index.xml is generated by the build process. It should not be commited to the repository.

### CODE REVIEW

**Comment by damien-rembert** [comment]
If it should never be committed, it might be good to add it to the .gitignore file?

**Comment by brandelune** [comment]
Does that work better this way?

**Comment by miurahr** [comment]
You are recommended to create `doc_src/.gitignore` for the purpose.

**Comment by miurahr** [comment]
rebase and merged into `master`

**Pull request closed without merging**
